tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "skeema/tap"
tap "homebrew/cask-fonts"


brew "neovim"
brew "vim"
brew "git"
brew "node"
brew "yarn"
brew "fish"
brew "fzf"
brew "ripgrep"
brew "tmux"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "awscli"
brew "cmake"
brew "curl"
brew "watch"
brew "wget"
brew "microsoft-edge"
brew "gh"

cask "font-fira-code-nerd-font"
cask "font-victor-mono"
cask "docker"
cask "insomnia"
cask "iterm2"
