#configs para Tmux

#shell por defecto
set -g default-command /usr/local/bin/fish
#set -g default-shell /bin/zsh
  
#tecla de prefijo de Tmux cambiada similar a Screen: Ctrl-a
#de Ctrl-b a Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix
    
#configuracion del retraso entre el prefijo y el comando
set -sg escape-time 1
     
#comienza numerando las ventanas desde el 1
set -g base-index 1
     
#comienza numerando los paneles desde el 1
setw -g pane-base-index 1

# re-enumera ventanas cuando se cierra una
set -g renumber-windows on
       
#recarga la configuracion de tmux y muestra un mensaje de confirmacion
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf recargado!"
         
#dividir la ventana horizontalmente
bind | split-window -h
          
#dividir la ventana verticalmente
bind - split-window -v
           
#movimiento entre los paneles como en Vim
# k
# h l
# j
#
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
            
#movimiento entre ventanas como en Vim
#
# prefijo + Ctrl-h prefijo + Ctrl-l
#<<<<<<<<<<<<<<<< >>>>>>>>>>>>>>>>
#
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
             
#redimencionado de paneles como las teclas de movimientos en Vim
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5
bind-key -r a resize-pane -L
bind-key -r s resize-pane -D
bind-key -r d resize-pane -U
bind-key -r f resize-pane -R
#### me parece mas rapido redimencionar con las flechas de direccion
              
#integracion con el raton
#setw -g mode-mouse on
               
#mas funciones para ejecutar con el raton
#set -g mouse-select-pane on
#set -g mouse-resize-pane on
#set -g mouse-select-window on
                
#Barra inferior tmux 
set -g default-terminal "screen-256color"
set -g status-left "#[bg=#006064] #H"
set -g status-right " #[default] %d/%m/%Y #[bg=#006064,bold] %H:%M"
set -g status-justify left 
set -g status-bg "#455A64"
set -g status-fg "#ffffff"
setw -g window-status-current-bg "#880E4F"
setw -g window-status-current-fg "#ffffff"
set -g window-status-current-format "#I #W"
set -g window-status-format "#I #W"
                       
#frecuencia de actualizacion de la barra de estado en segundos
set -g status-interval 2
                        
#Modo Vi para Tmux
setw -g mode-keys vi
                         
# portapapeles copiar
# Para copiar:
# - Presionas Ctrl A + [ para entrar en modo copiar.
# - Con el cursor mueves al inicio del contenido a copiar
# - Presionas ESPACIO para resaltar y seleccionar el texto a copiar
# - Presionas ENTER para salir
# - Presionas Ctrl A + Ctrl C para mandar el buffer de copiado de tmux al
# portapapeles
#bind C-c run "tmux save-buffer - | xclip -i -selection clipboard"
bind C-c run "tmux show-buffer | xsel -i -b"
#portapapeles pegar
#bind C-v run "tmux set-buffer -- \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"
bind C-v run "tmux set-buffer -- \"$(xsel -o -b)\"; tmux paste-buffer"
                          
                           
#############################################################
#############################################################
                            
#mejora el scroll con las teclas shift-PageUp/shift-PageDown
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
                 
#setw -g aggressive-resize on
